In [3]:
import numpy as np

In [4]:
a=np.arange(0,6)

In [5]:
a


array([0, 1, 2, 3, 4, 5])

In [6]:
type(a)

numpy.ndarray

In [10]:
b=np.linspace(0,10,7)

In [11]:
b

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [12]:
c=np.linspace(0,55,6) #it will generate evenlyspaced number 

In [13]:
c#such as 0 and 11 has diffference 

array([ 0., 11., 22., 33., 44., 55.])

In [14]:
d=np.linspace(0,55,7)

In [15]:
d

array([ 0.        ,  9.16666667, 18.33333333, 27.5       , 36.66666667,
       45.83333333, 55.        ])

In [16]:
e=np.ones((4,3))

In [17]:
e

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
f=np.eye(5)

In [25]:
f

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
mat=np.diag([12,23,45])
mat

array([[12,  0,  0],
       [ 0, 23,  0],
       [ 0,  0, 45]])

In [5]:
np.diag(mat)

array([12, 23, 45])

In [7]:
random_array=np.random.randint(1,121,6)
random_array

array([ 83,  31, 111,  42,  48, 116])

In [9]:
ar=np.random.rand(6)
ar

array([0.11434859, 0.33402994, 0.21745836, 0.64269338, 0.81799476,
       0.12976467])

In [10]:
ar1=np.random.randn(10)

In [11]:
ar1

array([ 0.22570628, -0.41787686,  1.41403311, -0.20492151,  0.96784673,
        0.13041983,  1.82357076, -1.76191079,  0.08445991, -1.22267286])

In [13]:
ae=np.array([[1,2,3,4],[22,33,44,55]])

In [14]:
ae


array([[ 1,  2,  3,  4],
       [22, 33, 44, 55]])

In [15]:
arr1=np.arange(54)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53])

In [16]:
a_1=arr1.reshape(9,6)

In [17]:
a_1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53]])

In [18]:
a3=np.array([[23,12,5],[34,11,23]])
a3

array([[23, 12,  5],
       [34, 11, 23]])

In [19]:
np.sort(a3,axis=0)

array([[23, 11,  5],
       [34, 12, 23]])

In [20]:
np.sort(a3,axis=1)

array([[ 5, 12, 23],
       [11, 23, 34]])

In [25]:
a3 = np.append(a3,[56,34,59])
a3

array([23, 12,  5, 34, 11, 23, 56, 34, 59, 56, 34, 59])

In [27]:
a11=a3.reshape(4,3)
a11

array([[23, 12,  5],
       [34, 11, 23],
       [56, 34, 59],
       [56, 34, 59]])

In [29]:
a11[2,2]=45

In [30]:
a11

array([[23, 12,  5],
       [34, 11, 23],
       [56, 34, 45],
       [56, 34, 59]])

In [31]:
if a11[0,2]==5:
    print("true")
else:
    print("false")

true


In [32]:
l1=np.arange(4,18)
l1

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [36]:
l1[0:14:3]

array([ 4,  7, 10, 13, 16])

In [3]:
ar1=np.random.randint(0,20,5)
ar1

array([ 2, 17, 10, 15, 16])

In [5]:
ar1[ar1%2==0]

array([ 2, 10, 16])

In [8]:
ar1[ar1%2==0]=-1
ar1

array([-1, 17, -1, 15, -1])

In [10]:
ar=np.random.randint(0,101,60)
ar

array([98,  9,  4, 24, 25, 48, 56, 93, 57, 54, 75, 23, 17, 29, 20, 25, 67,
       87, 49, 13, 54, 17, 30, 49, 90, 56, 51, 66, 14, 39, 36, 49, 37, 98,
       76, 92, 59, 75, 22, 95, 69, 13, 66, 14, 70, 16, 39, 59, 87, 86, 91,
       42,  9, 20, 29, 38, 80, 23, 44,  0])

In [15]:
ar[[3,8,21,45,2,3,45,23,33,44]]

array([24, 57, 17, 16,  4, 24, 16, 49, 98, 70])

In [17]:
ar[[8,45]]=1000
ar


array([  98,    9,    4,   24,   25,   48,   56,   93, 1000,   54,   75,
         23,   17,   29,   20,   25,   67,   87,   49,   13,   54,   17,
         30,   49,   90,   56,   51,   66,   14,   39,   36,   49,   37,
         98,   76,   92,   59,   75,   22,   95,   69,   13,   66,   14,
         70, 1000,   39,   59,   87,   86,   91,   42,    9,   20,   29,
         38,   80,   23,   44,    0])

In [21]:
b=np.diag([2,3,4,6])
b

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [30]:
d=[print(b*b)]

[[ 4  0  0  0]
 [ 0  9  0  0]
 [ 0  0 16  0]
 [ 0  0  0 36]]


In [25]:
print(b**3)

[[  8   0   0   0]
 [  0  27   0   0]
 [  0   0  64   0]
 [  0   0   0 216]]


In [73]:
a=np.array([[1,2,3],[5,6,7]])
b=np.array([[3,2],[5,3],[2,5]])
np.matmul(a,b)

array([[19, 23],
       [59, 63]])

In [41]:
np.matmul(b,a)

array([[37, 48, 71],
       [48, 63, 92],
       [53, 68, 95]])

In [43]:
c=np.array([[1,3],[2,4]])
d=np.array([[6,7],[8,9]])
np.matmul(c,d)

array([[30, 34],
       [44, 50]])

In [44]:
np.matmul(d,c)

array([[20, 46],
       [26, 60]])

In [50]:
e=np.array([1,2,3,4])
f=np.array([4,5,3,4])
e==f


array([False, False,  True,  True])

In [51]:
a=np.array([1,1,0,0], dtype=bool)
b=np.array([1,0,1,0], dtype=bool)
np.logical_or(a,b)


array([ True,  True,  True, False])

In [62]:
a=np.array([1,1,0,0], dtype=int)
b=np.array([1,0,1,0], dtype=int)
a+b
#np.logical_or(a,b)


array([2, 1, 1, 0])

In [58]:
a+b

array([2, 1, 1, 0])

In [63]:
a=np.array([2,1,0,0], dtype=bool)
b=np.array([1,3,1,4], dtype=bool)

In [64]:
a+b

array([ True,  True,  True,  True])

In [65]:
a=np.array([2,1,0,0], dtype=float)
b=np.array([1,3,1,4], dtype=float)
a+b

array([3., 4., 1., 4.])

In [74]:
y=np.array([3,4,5,6])
np.sum(y)

18

In [76]:
x=np.array([[1,2],[3,4]])
np.sum(x,axis=0)

array([4, 6])

In [77]:
x.sum()

10

In [79]:
np.sum(x)

10

In [81]:
z=np.array([3,5,6])
z.min()

3

In [83]:
np.argmin(z) # this is for min and for max only the min will be replaced with max


0

In [4]:
a=np.random.randn(10)
a

array([-0.86955803, -0.95597742,  1.02890116,  0.6839984 , -0.84459969,
        1.15286955,  0.19277423,  0.74805785, -0.55453132, -2.16956283])

In [5]:
ar_2=np.arange(4)
np.sin(ar_2)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [6]:
np.log(ar_2)

C:\Users\Dell Pc\AppData\Local\Temp\ipykernel_10000\1942121967.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(ar_2)


array([      -inf, 0.        , 0.69314718, 1.09861229])

In [7]:
np.exp(ar_2)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [8]:
y=np.array([[1,3,4,6,7],[2,7,4,8,9]])
y.sum(axis=0)


array([ 3, 10,  8, 14, 16])

In [9]:
y.sum(axis=1)

array([21, 30])

In [13]:
arr=np.arange(3,55,2)
print('Array is ',format(arr))

print('Max element in the array is ',np.max(arr))

print('Min element in the array is ',np.min(arr))

print('Sum of all the elements of the array is ',np.sum(arr))

print('Mean of elements present in the array is ',np.mean(arr))

print('Median of the elements present in the array is ',np.median(arr))

print('Standard deviation of elements in the array is ',np.std(arr))

Array is  [ 3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49
 51 53]
Max element in the array is  53
Min element in the array is  3
Sum of all the elements of the array is  728
Mean of elements present in the array is  28.0
Median of the elements present in the array is  28.0
Standard deviation of elements in the array is  15.0
